In [1]:
import math
n=8
rows, cols = (n, n)
t = [[0 for i in range(cols)] for j in range(rows)]
for i in range(n):
    for j in range(n):
        if(i==0):
            t[i][j]=1/math.sqrt(n)
        else:
            t[i][j]=math.sqrt(2.0/n)*math.cos((2*j+1)*i*math.pi/2/n)
print(t)

[[0.35355339059327373, 0.35355339059327373, 0.35355339059327373, 0.35355339059327373, 0.35355339059327373, 0.35355339059327373, 0.35355339059327373, 0.35355339059327373], [0.4903926402016152, 0.4157348061512726, 0.27778511650980114, 0.09754516100806417, -0.0975451610080641, -0.277785116509801, -0.4157348061512727, -0.4903926402016152], [0.46193976625564337, 0.19134171618254492, -0.19134171618254486, -0.46193976625564337, -0.4619397662556434, -0.19134171618254517, 0.191341716182545, 0.46193976625564326], [0.4157348061512726, -0.0975451610080641, -0.4903926402016152, -0.2777851165098011, 0.2777851165098009, 0.4903926402016152, 0.09754516100806439, -0.41573480615127256], [0.3535533905932738, -0.35355339059327373, -0.35355339059327384, 0.3535533905932737, 0.35355339059327384, -0.35355339059327334, -0.35355339059327356, 0.3535533905932733], [0.27778511650980114, -0.4903926402016152, 0.09754516100806415, 0.4157348061512728, -0.41573480615127256, -0.09754516100806401, 0.4903926402016153, -0.2

In [35]:
import math
t=[]
t = [[0 for i in range(cols)] for j in range(rows)]
for i in range(n):
    for j in range(n):
        if(i==0):
            t[i][j]=1/math.sqrt(n)
        else:
            t[i][j]=math.sqrt(2.0/n)*math.cos((2*j+1)*i*math.pi/2/n)
print(np.array(t))

[[ 0.35355339  0.35355339  0.35355339  0.35355339  0.35355339  0.35355339
   0.35355339  0.35355339]
 [ 0.49039264  0.41573481  0.27778512  0.09754516 -0.09754516 -0.27778512
  -0.41573481 -0.49039264]
 [ 0.46193977  0.19134172 -0.19134172 -0.46193977 -0.46193977 -0.19134172
   0.19134172  0.46193977]
 [ 0.41573481 -0.09754516 -0.49039264 -0.27778512  0.27778512  0.49039264
   0.09754516 -0.41573481]
 [ 0.35355339 -0.35355339 -0.35355339  0.35355339  0.35355339 -0.35355339
  -0.35355339  0.35355339]
 [ 0.27778512 -0.49039264  0.09754516  0.41573481 -0.41573481 -0.09754516
   0.49039264 -0.27778512]
 [ 0.19134172 -0.46193977  0.46193977 -0.19134172 -0.19134172  0.46193977
  -0.46193977  0.19134172]
 [ 0.09754516 -0.27778512  0.41573481 -0.49039264  0.49039264 -0.41573481
   0.27778512 -0.09754516]]


In [40]:
imag=[[154,123,123,123,123,123,123,136],[192,180,136,154,154,154,136,110],[254,198,154,154,180,154,123,123]
     ,[239,180,136,180,180,166,123,123],[180,154,136,167,166,149,136,136],[128,136,123,136,154,180,198,154]
     ,[123,105,110,149,136,136,180,166],[110,136,123,123,123,136,154,136]]
print(np.array(imag))

[[154 123 123 123 123 123 123 136]
 [192 180 136 154 154 154 136 110]
 [254 198 154 154 180 154 123 123]
 [239 180 136 180 180 166 123 123]
 [180 154 136 167 166 149 136 136]
 [128 136 123 136 154 180 198 154]
 [123 105 110 149 136 136 180 166]
 [110 136 123 123 123 136 154 136]]


In [41]:
import numpy as np
a = [[128] * n] * n
resident=np.array(imag)-np.array(a)
print(resident)
print(np.array(t))
print(np.transpose(t))

[[ 26  -5  -5  -5  -5  -5  -5   8]
 [ 64  52   8  26  26  26   8 -18]
 [126  70  26  26  52  26  -5  -5]
 [111  52   8  52  52  38  -5  -5]
 [ 52  26   8  39  38  21   8   8]
 [  0   8  -5   8  26  52  70  26]
 [ -5 -23 -18  21   8   8  52  38]
 [-18   8  -5  -5  -5   8  26   8]]
[[ 0.35355339  0.35355339  0.35355339  0.35355339  0.35355339  0.35355339
   0.35355339  0.35355339]
 [ 0.49039264  0.41573481  0.27778512  0.09754516 -0.09754516 -0.27778512
  -0.41573481 -0.49039264]
 [ 0.46193977  0.19134172 -0.19134172 -0.46193977 -0.46193977 -0.19134172
   0.19134172  0.46193977]
 [ 0.41573481 -0.09754516 -0.49039264 -0.27778512  0.27778512  0.49039264
   0.09754516 -0.41573481]
 [ 0.35355339 -0.35355339 -0.35355339  0.35355339  0.35355339 -0.35355339
  -0.35355339  0.35355339]
 [ 0.27778512 -0.49039264  0.09754516  0.41573481 -0.41573481 -0.09754516
   0.49039264 -0.27778512]
 [ 0.19134172 -0.46193977  0.46193977 -0.19134172 -0.19134172  0.46193977
  -0.46193977  0.19134172]
 [ 0.0975451

In [42]:
D1=np.matmul(np.array(t),resident)
D2=np.matmul(D1,np.transpose(t))
print(D2)
print(D2[0,0])

[[ 1.62250000e+02  4.05989816e+01  2.00026918e+01  7.23294009e+01
   3.02500000e+01  1.24848354e+01 -1.96505043e+01 -1.14971452e+01]
 [ 3.04792937e+01  1.08415970e+02  1.04730992e+01  3.22925175e+01
   2.76990885e+01 -1.55048925e+01  1.84075948e+01 -1.99566961e+00]
 [-9.41445075e+01 -6.00511329e+01  1.22980970e+01 -4.34188963e+01
  -3.12878702e+01  6.06690905e+00 -3.33058262e+00  7.14403453e+00]
 [-3.85675018e+01 -8.33575149e+01 -5.41238759e+00 -2.21698602e+01
  -1.35195286e+01  1.54918916e+01 -1.33187181e+00  3.53461026e+00]
 [-3.12500000e+01  1.79340053e+01 -5.52404638e+00 -1.23555600e+01
   1.42500000e+01 -5.96236717e+00  1.14884686e+01 -6.02384997e+00]
 [-8.64681444e-01 -1.17637950e+01  1.27762672e+01  1.81231416e-01
   2.80712006e+01  1.25731431e+01  8.35255975e+00  2.93590135e+00]
 [ 4.62997947e+00 -2.42141001e+00  1.21694174e+01  6.56145155e+00
  -1.87001117e+01 -1.27532960e+01  7.70190296e+00  1.20313688e+01]
 [-9.95302906e+00  1.11936702e+01  7.81185357e+00 -1.62885238e+01
   

In [45]:
quatization=[[16,11,10,16,24,40,51,61],[12,12,14,19,26,58,60,55],[14,13,16,24,40,57,69,56]
     ,[14,17,22,29,51,87,80,62],[18,22,37,56,68,109,103,77],[24,35,55,64,81,104,113,92]
     ,[49,64,78,87,103,121,120,101],[72,92,95,98,112,100,103,99]]
print(np.array(quatization))

[[ 16  11  10  16  24  40  51  61]
 [ 12  12  14  19  26  58  60  55]
 [ 14  13  16  24  40  57  69  56]
 [ 14  17  22  29  51  87  80  62]
 [ 18  22  37  56  68 109 103  77]
 [ 24  35  55  64  81 104 113  92]
 [ 49  64  78  87 103 121 120 101]
 [ 72  92  95  98 112 100 103  99]]


In [68]:
compressed_img = [[0 for i in range(n)] for j in range(n)]
for i in range(n):
    for j in range(n):
        compressed_img[i][j]=round(np.array(D2)[i,j]/np.array(quatization)[i,j])
print(np.array(compressed_img))

[[10  4  2  5  1  0  0  0]
 [ 3  9  1  2  1  0  0  0]
 [-7 -5  1 -2 -1  0  0  0]
 [-3 -5  0 -1  0  0  0  0]
 [-2  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


In [72]:
reconstruct=[[0 for i in range(n)] for j in range(n)]
for i in range(n):
    for j in range(n):
        reconstruct[i][j]=np.array(compressed_img)[i,j]*np.array(quatization)[i,j]
print(np.array(reconstruct))
        

[[160  44  20  80  24   0   0   0]
 [ 36 108  14  38  26   0   0   0]
 [-98 -65  16 -48 -40   0   0   0]
 [-42 -85   0 -29   0   0   0   0]
 [-36  22   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]


In [73]:
DD1=np.matmul(np.transpose(t),np.array(reconstruct))
DD2=np.matmul(DD1,np.array(t))
print(DD2)
print(DD2[0,0])

[[ 21.0273001    5.97629413  -8.67882808 -11.77259762  -6.85553496
   -2.30714869  -0.63883177  -0.24716454]
 [ 75.57894855  40.04333817  12.42272956  15.61077217  27.10249145
   22.46167858   7.05083176  -3.38871244]
 [124.80005101  67.33313686  27.17981894  38.23142773  54.88468049
   37.17301999   3.06502266 -17.08924785]
 [116.56422396  56.95298416  20.03831505  38.0704498   55.56614254
   32.44623523  -3.66811745 -20.99549684]
 [ 59.50566369  21.39371022   4.18700469  26.67910472  44.42837212
   31.46366425  12.9668558    8.48722917]
 [  3.55661884  -5.4526821   -3.38453989  14.86279648  31.95485081
   37.65757261  39.81802474  43.48388431]
 [-18.57752636  -8.61317547  -2.46891889  -0.1635312   11.38525277
   30.13471709  39.57942539  37.76724324]
 [-17.22421911  -1.1431078   -0.51211285 -14.36570537  -9.88149052
   12.53894838  18.98413471   7.01372287]]
21.027300099160676


In [77]:
DD3=[[0 for i in range(n)] for j in range(n)]
for i in range(n):
    for j in range(n):
        DD3[i][j]=round(DD2[i][j])+128
print(np.array(DD3))

[[149 134 119 116 121 126 127 128]
 [204 168 140 144 155 150 135 125]
 [253 195 155 166 183 165 131 111]
 [245 185 148 166 184 160 124 107]
 [188 149 132 155 172 159 141 136]
 [132 123 125 143 160 166 168 171]
 [109 119 126 128 139 158 168 166]
 [111 127 127 114 118 141 147 135]]


In [85]:
a=[]
type(a)
isinstance(a, list)
help(a)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [87]:
DD3=[[0 for i in range(n)] for j in range(n)]
type(DD3)

list

In [96]:
a=[1,2,3]
type(a)

list

In [92]:
cars = ["Ford", "Volvo", "BMW"]
type(cars)
len(cars)

3

In [97]:
a.remove(2)
print(a)

[1, 3]


In [102]:
print(type('string'))
print(type(type('string')))
print(type(type(1)))
print(type('string') is str)
print(type('string') is int)


<class 'str'>
<class 'type'>
<class 'type'>
True
False
